#Kavish Nag
#240701260885
#AIML B1

In [ ]:
from sklearn.metrics import DistanceMetric
dist=DistanceMetric.get_metric('euclidean') #uses euclidean form to calculate distance
X=[[1,2],[3,4],[5,6]]
Y=[[7,8],[9,10]]
dist.pairwise(X,Y)

array([[ 8.48528137, 11.3137085 ],
       [ 5.65685425,  8.48528137],
       [ 2.82842712,  5.65685425]])

In [ ]:
from sklearn.metrics import DistanceMetric
dist=DistanceMetric.get_metric('manhattan') #uses manhattan form to calculate distance
X=[[1,2],[3,4],[5,6]]
Y=[[7,8],[9,10]]
dist.pairwise(X,Y)

array([[12., 16.],
       [ 8., 12.],
       [ 4.,  8.]])

In [ ]:
from sklearn.metrics import DistanceMetric
dist=DistanceMetric.get_metric('chebyshev') #uses chebyshev form to calculate distance
X=[[1,2],[3,4],[5,6]]
Y=[[7,8],[9,10]]
dist.pairwise(X,Y)

array([[6., 8.],
       [4., 6.],
       [2., 4.]])

In [ ]:
from sklearn.metrics import DistanceMetric
dist=DistanceMetric.get_metric('minkowski') #uses minkowski form to calculate
X=[[1,2],[3,4],[5,6]]
Y=[[7,8],[9,10]]
dist.pairwise(X,Y)

array([[ 8.48528137, 11.3137085 ],
       [ 5.65685425,  8.48528137],
       [ 2.82842712,  5.65685425]])

In [ ]:
from skimage.io import imread
import numpy as np
i1=imread("/content/OAS1_0028_MR1_mpr-1_100.jpg",as_gray=True)
i2=imread("/content/OAS1_0028_MR1_mpr-1_101.jpg",as_gray=True)

v1= i1.flatten()
v2= i2.flatten()

dist1=DistanceMetric.get_metric('euclidean')
dist1.pairwise([v1],[v2])

array([[18.74790446]])

In [ ]:
dist2=DistanceMetric.get_metric('manhattan')
dist2.pairwise([v1],[v2])

array([[3567.79607843]])

In [ ]:
dist3=DistanceMetric.get_metric('chebyshev')
dist3.pairwise([v1],[v2])

array([[0.73333333]])

In [ ]:
i3=imread("/content/OAS1_0028_MR1_mpr-1_129.jpg",as_gray=True)
v3=i3.flatten()
dist1.pairwise([v1],[v3])

array([[73.43145925]])

In [ ]:
dist2.pairwise([v1],[v3])

array([[16057.22745099]])

In [ ]:
dist3.pairwise([v1],[v3])

array([[0.99215686]])